"""
Django settings for FriendsAtHome project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.core.management.commands.runserver import Command as runserver
import base64
import os


runserver.default_port = "8001"


CSP_ENABLE = True

KLARNA_API_USERNAME = 'PK85112_7e1a7ac12aca'
KLARNA_API_PASSWORD = 'KBIdHmtTZL3xJbpq'
KLARNA_API_ENDPOINT = 'https://api.playground.klarna.com/'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&w7&0=490te$vu5g_nnmq(qzt-e@rmto93mvfeb7a#38y6f(!f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'sslserver',
    'csp',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    
 
]



ROOT_URLCONF = 'FriendsAtHome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FriendsAtHome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Lägg till SSL-certifikat och nyckel
SECURE_SSL_REDIRECT = True
SECURE_SSL_HOST = '127.0.0.1:8001'  # Ange din domän här om det är en testdomän

 #Ange sökvägen till ditt certifikat och nyckel
SECURE_SSL_CERTIFICATE = '/Users/mansoxelstrom/Desktop/SSL/mycert.pem'
SECURE_SSL_KEY = '/Users/mansoxelstrom/Desktop/SSL/mykey.key'

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# Content Security Policy (CSP) inställningar för Klarna och Font Awesome

CSP_DEFAULT_SRC = ("'self'", "https://*.klarna.com", "'unsafe-inline'")

CSP_SCRIPT_SRC = ("'self'", "https://*.klarna.com", "'unsafe-inline'")

CSP_FRAME_SRC = ("'self'", "https://*.klarna.com", "'unsafe-inline'")

# Font Awesome (ta med de domäner som ditt Font Awesome-paket använder)
CSP_STYLE_SRC = ("'self'", "https://*.klarna.com", "https://use.fontawesome.com/", "'unsafe-inline'" )  # Exempel för användning av Font Awesome via CDN
CSP_IMG_SRC = ("'self'", "https://*.klarnaevt.com","https://*.klarna.com", "'unsafe-inline'")
CSP_CONNECT_SRC = ("'self'", "https://*.klarnaevt.com", "https://*.klarna.com", "'unsafe-inline'")


CSP_FONT_SRC = ("'self'", "https://*.klarnaevt.com", "https://*.klarna.com", "https://use.fontawesome.com/", "'unsafe-inline'")
# ... andra CSP-inställningar ...


