# Generated by Django 4.2.5 on 2023-10-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_klarnaorder_order_id_alter_klarnaorder_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='KlarnaOrder',
        ),
    ]
