# Generated by Django 4.2.5 on 2024-01-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='kvantitet',
        ),
    ]
